spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yvonnkr/environment-variables-repo.git
          default-label: main

server:
  port: ${port:8888}

