spring:
  application:
    name: product-enquiry-service

server:
  port: ${port:8700}

# Before Adding Eureka-server
#product-stock-service:
#  ribbon:
#    listOfServers: http://localhost:8800, http://localhost:8801